/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Controlador;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author gx160
 */
public class GUITableroo extends javax.swing.JFrame {
    private ImageIcon tablero;
    private Controlador controlador;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUITableroo.class.getName());

    /**
     * Creates new form GUITableroo
     */
    public GUITableroo() {
     
    }

    public void setLblCronometro(JLabel lblCronometro) {
        this.lblCronometro = lblCronometro;
    }

    public JLabel getLblCronometro() {
        return lblCronometro;
    }

    /**
        initComponents();
    }
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanelTablero = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnArriba = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        btnDerecha = new javax.swing.JButton();
        btnAbajo = new javax.swing.JButton();
        btnLanzarDado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblResultadoDado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCronometro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFichaJugador1 = new javax.swing.JLabel();
        lblFicha1Jugador2 = new javax.swing.JLabel();
        lblPuntajepersonaje1 = new javax.swing.JLabel();
        lblpuntajePersonaje2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFicha2jugador1 = new javax.swing.JLabel();
        lblFicha3Jugador1 = new javax.swing.JLabel();
        lblFicha4jugador1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3fondoplantas.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaArriba.png"))); // NOI18N
        btnArriba.setContentAreaFilled(false);
        btnArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArribaActionPerformed(evt);
            }
        });
        jPanel2.add(btnArriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        btnIzquierda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaIzquierda.png"))); // NOI18N
        btnIzquierda.setContentAreaFilled(false);
        jPanel2.add(btnIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        btnDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaDerecha.png"))); // NOI18N
        btnDerecha.setContentAreaFilled(false);
        jPanel2.add(btnDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        btnAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flechaAbajo.png"))); // NOI18N
        btnAbajo.setBorderPainted(false);
        btnAbajo.setContentAreaFilled(false);
        btnAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAbajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 130, -1));

        btnLanzarDado.setText("lanzar dado");
        jPanel2.add(btnLanzarDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descarga.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 229, 155));

        lblResultadoDado.setText("resultado dado");
        jPanel2.add(lblResultadoDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 130, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3fondoplantas.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 830));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ArbolDorado.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -250, -1, -1));

        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lblCronometro.setText("lblTablero");
        jPanel2.add(lblCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        javax.swing.GroupLayout jPanelTableroLayout = new javax.swing.GroupLayout(jPanelTablero);
        jPanelTablero.setLayout(jPanelTableroLayout);
        jPanelTableroLayout.setHorizontalGroup(
            jPanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTableroLayout.setVerticalGroup(
            jPanelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        lblFichaJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gx160frijolFicha.png"))); // NOI18N
        getContentPane().add(lblFichaJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, -1, -1));

        lblFicha1Jugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frijolnegro.png"))); // NOI18N
        getContentPane().add(lblFicha1Jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, 50));

        lblPuntajepersonaje1.setText("jLabel6");
        getContentPane().add(lblPuntajepersonaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 80, 60));

        lblpuntajePersonaje2.setText("jLabel6");
        getContentPane().add(lblpuntajePersonaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 90, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolDorado.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -200, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arbolDorado.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        lblFicha2jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gx160frijolFicha.png"))); // NOI18N
        getContentPane().add(lblFicha2jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        lblFicha3Jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gx160frijolFicha.png"))); // NOI18N
        getContentPane().add(lblFicha3Jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, -1, -1));

        lblFicha4jugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gx160frijolFicha.png"))); // NOI18N
        getContentPane().add(lblFicha4jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frijolnegro.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frijolnegro.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frijolnegro.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 10, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 30, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 30, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tablero parchis.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3fondoplantas.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -40, 880, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbajoActionPerformed

    private void btnArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArribaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArribaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUITableroo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAbajo;
    public javax.swing.JButton btnArriba;
    public transient javax.swing.JButton btnDerecha;
    public javax.swing.JButton btnIzquierda;
    public javax.swing.JButton btnLanzarDado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelTablero;
    public javax.swing.JLabel lblCronometro;
    private javax.swing.JLabel lblFicha1Jugador2;
    private javax.swing.JLabel lblFicha2jugador1;
    private javax.swing.JLabel lblFicha3Jugador1;
    private javax.swing.JLabel lblFicha4jugador1;
    private javax.swing.JLabel lblFichaJugador1;
    private javax.swing.JLabel lblPuntajepersonaje1;
    private javax.swing.JLabel lblResultadoDado;
    private javax.swing.JLabel lblpuntajePersonaje2;
    // End of variables declaration//GEN-END:variables
}
